# Generated by Django 3.0.8 on 2020-07-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turismo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
